name: Build and Deploy to GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: devops-cluster
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: nginx-k8s
  IMAGE: nginx

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

     # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.CREDENTIALS_JSON }}

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v2

    - name: 'Deploy with gke-deploy cli'
      uses: 'google-github-actions/deploy-gke-container@v0.1'
      with:
        image: nginx
        app_name: 'nginx-deployment'
        region: 'us-central1'
        cluster_name: 'devops-cluster'
        project_id: 'devops-437919'
        expose: '80'

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl get services -o wide