name: Build and Deploy to GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: devops-cluster
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: nginx-deployment
  IMAGE: nginx

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

     # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.CREDENTIALS_JSON }}

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v2

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        gcloud auth list
        kubectl get services -o wide